# Generated by Django 3.2.12 on 2022-08-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='images')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_author', models.CharField(max_length=20)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
