# Generated by Django 3.2.15 on 2022-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post_approved',
            field=models.BooleanField(default=False),
        ),
    ]
