# Generated by Django 3.2.15 on 2023-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_is_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
